Wikipedia Fearure Added
TobiasDemuth/Assistant-Ghost pull request #18
Opened 2024-02-15 05:20 UTC by Abhi13e

Wikipedia feature added. We have to speak "wikipedia (anything you want to get information)" afterward it will give  information in audio and save in conversation.txt.

2024-02-15 08:48 UTC, Abhi13e commented
@TobiasDemuth Hey have you review my code? ..... is anything required to change more?

2024-02-15 13:04 UTC, TobiasDemuth commented on speech_assistent.py
> +                with open("conversation.txt", "a") as file:
conversation writing is handled at the end of the file so it can be deleted

2024-02-15 13:07 UTC, TobiasDemuth requested changes
so delete the conversation handling you added and adjust input handling like the comment sais the rest looks just fine :)

2024-02-15 18:30 UTC, TobiasDemuth approved these changes

2024-02-15 18:30 UTC, merged

2024-02-16 06:39 UTC, Abhi13e commented
Hey @TobiasDemuth i need to change or you already make changes in that?

2024-02-16 06:51 UTC, TobiasDemuth commented
@Abhi13e already changed no worries :)